name: seismic-interp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - pytorch
  - pytorch-lightning
  - obspy
  - jupyter
  - jupyterlab
  - mlflow
